services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: dockerfile

    envVars:
      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: WEBHOOK_URL
        value: https://n8n-render-r847.onrender.com

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: N8N_RUNNERS_ENABLED
        value: "true"

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      - key: TZ
        value: Asia/Kolkata