services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: Dockerfile

    envVars:
      - key: N8N_HOST
        value: 0.0.0.0

      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: WEBHOOK_URL
        value: https://n8n-render-r847.onrender.com/

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_CONNECTION_STRING
        value: postgresql://n8n_practice_lx28_user:UdSq567QCArCjAKrIppDjM1UCdSuc2Bj@dpg-d7u39dpkh4rs738eji3g-a.singapore-postgres.render.com/n8n_practice_lx28

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: N8N_RUNNERS_ENABLED
        value: "true"

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      - key: TZ
        value: Asia/Kolkata

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

      - key: N8N_BASIC_AUTH_USER
        value: admin

      - key: N8N_BASIC_AUTH_PASSWORD
        value: password123